version: "3.2"
services:
  tinchat-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: tinchat-server
    container_name: tinchat-server
    restart: unless-stopped
    env_file: .env
    ports:
      - 8000:8000
    command: yarn start
  db:
    image: postgres
    restart: unless-stopped
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    ports:
      - "5432:5432"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    restart: unless-stopped
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256M -Xmx256M"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - network.host=_eth0_
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
  esdata:
    driver: local