version: "3.2"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
